bdms_main/urls.py
from django.contrib import admin 
from django.urls import path, include
#from django.conf import settings
#from django.conf.urls.static import static
#from bdmapp.common.views import HomeView, SignUpView, AboutView
from bdmapp.common.views import HomeView, SignUpView, AboutView, ProfileUpdateView, ProfileView, DonationView
from bdmapp.common import views
from bdmapp.common.views import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('donation/', DonationView.as_view(), name='donation'),
   # path('contact/',views.contact, name="contact"),
    #path('send-form-email/', views.SendFormEmail.as_view(), name='send_mail'),
    
    #path('donation/',views.doner),
    path('excel/', views.ExcelPageView.as_view(), name='excel'), 
    path('export/excel', views.export_users_xls, name='export_excel'),
    path('export/excel-styling', views.export_styling_xls, name='export_styling_excel'),
    path('export/export-write-xls', views.export_write_xls, name='export_write_xls'),
    
    path('contact/',views.ContactView.as_view(), name="contact"),

    path('profile-update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # Authentication 
    path('register/', SignUpView.as_view(), name="register"),

    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'
        ),
        name='login'
    ),

    path('logout/', auth_views.LogoutView.as_view(
        next_page='home'
        ),
        name='logout' 
    ),

    path(
        'change-password',
        auth_views.PasswordChangeView.as_view(
            template_name='common/change-password.html',
            success_url='/'
        ),
        name='change-password'
    ),

    
    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='common/password-reset/password_reset.html',
             subject_template_name='common/password-reset/password_reset_subject.txt',
             email_template_name='common/password-reset/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='common/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='common/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='common/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('oauth/', include('social_django.urls', namespace='social')),  # <-- here 

]#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bdmapp/doner_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime, date

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Full_Name = models.CharField(max_length=500, blank=False)
    gender=( ('male',"MALE"),('female',"FEMALE"),('other',"OTHER"))
    Gender = models.CharField(max_length=50, choices=gender, blank=False)
    Age = models.CharField(max_length=50, blank=False)
    bg=(('A+',"A+"),('A-',"A-"),('B+',"B+"),('B-',"B-"),('AB+',"AB+"),('AB-',"AB-"),('O+',"O+"),('O-',"O-"))
    Blood_Group = models.CharField(max_length=50, choices=bg, blank=False)
    pro=(('Student',"student"),('Service',"service"),('Job seeker',"job seeker"),('Housewife',"housewife"),('Others',"others"))
    Profession = models.CharField(max_length=50, choices=pro, blank=True)
    Home_District = models.CharField(max_length=50, blank=True)
    Present_Address = models.CharField(max_length=300, blank=False)
    Last_Donation_Date = models.DateField(null=True, blank=True)
    Phone_Number = models.CharField(max_length=11, blank=False)
    Email = models.CharField(max_length=300, blank=True)
    Profile_Image = models.ImageField(default='800px-Blood_donation_pictogram.svg.png', upload_to='users/', null=True, blank=True)    
    added = models.DateTimeField( auto_now=False, auto_now_add=True)
    updated = models.DateTimeField( auto_now=True, auto_now_add=False)

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>BDMS/about</title>
  <link rel="icon" type="image/png" href="blood_drop.png"/>

  <!-- Custom fonts for this template-->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  
  
  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  
   <!--date time picker css-->
   <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui.css' %}">
  <link rel='stylesheet' href="{% static 'date-time-phone/jquery-ui-timepicker-addon.css' %}" />
  
  <!--mail css-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-address-card"></i>
        </div>
        <div class="sidebar-brand-text mx-3"><font color="orange">Blood donation <sup>Management</sup></font></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Doners -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'donation' %}">
          <i class="fas fa-user-plus"></i>
          <span><strong><font color="yellow" size="3">Donors</font></strong></span></a>
      </li>

      <!-- Nav Item - Contact -->
     <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">
          <i class="fas fa-envelope"></i>
          <span><strong><font color="yellow" size="3">contact</font></strong></span></a>
      </li>


      <!-- Nav Item - Contact -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'excel' %}">
          <i class="fas fa-address-book"></i>
          <span><strong><font color="yellow" size="3">View</font></strong></span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Profile -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profile' %}">
          <i class="fas fa-fw fa-user"></i>
          <span><strong><font color="yellow" size="3">Profile</font></strong></span></a>
      </li>

      <!-- Nav Item - Change Password -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'change-password' %}">
          <i class="fas fa-fw fa-key"></i>
          <span><strong><font color="yellow" size="3">Change Password</font></strong></span></a>
      </li>

      <!-- Nav Item - Logout -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">
          <i class="fas fa-fw fa-sign-out-alt"></i>
          <span><strong><font color="yellow" size="3">Logout</font></strong></span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        {% include 'common/messages.html' %}

        {% block content %}  {% endblock content %}


      </div>
      <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

   <!-- Bootstrap core JavaScript-->
   <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
   <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
 
   <!-- Core plugin JavaScript-->
   <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
 
   <!-- Custom scripts for all pages-->
   <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
 
   <script>
     setTimeout(function(){
       if ($('#msg').length > 0) {
         $('#msg').remove();
       }
     }, 2000)
   </script>

   <script src="{% static 'date-time-phone/jquery-ui.js' %}" ></script>
   <script src="{% static 'date-time-phone/jquery-ui-timepicker-addon.js' %}"></script> 

<script>
  $( function() {
     // $( "#id_Last_Donation_Date_Year_Month_Day" ).datetimepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
     // $( "#id_birth_date" ).timepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
       $( "#id_Last_Donation_Date_Year_Month_Day" ).datepicker({ dateFormat: 'yy-mm-dd' }).attr("autocomplete", "off") ;
  });
  </script>

  <script src="{% static 'date-time-phone/jquery-input-mask-phone-number.min.js' %}"></script>

<script>
  //(xxx) xxx-xxxx format code
  $(document).ready(function () {
      $('#id_Phone_Number').usPhoneFormat({
          format: 'xxxxx-xxxxxx',
      });   
  });
  </script>

</body>

</html>

templates/example.html
{% extends 'base.html' %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
        <h1 class="h3 mb-0 text-gray-800"><blockquote><font color="green">Life For Lifes</font></blockquote></h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
        </div>          

        <!-- Main Content Here -->



    </div>
    <!-- /.container-fluid -->
{% endblock content %}